# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  armDeploy:
     runs-on: ubuntu-latest

     steps:
     
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group rg-gethubactions
        uses: Azure/arm-deploy@v2
        with: 
            scope: subscription
            subscriptionId: 7bf02640-86d1-4a5d-a094-4f15f0d06661
            region: eastus
            template: ./arm-templates/resourcegroup.json
            deploymentName: rg-gethubactions

      